import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import 'swiper/css';
import 'swiper/css/pagination';
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import ContextProvider from "@/Context/context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Oporooms",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()

  return (
    <html lang="en">
      <script id="GoogleMaps" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBOjiEhtSB9GwO0UJGqzlDkJvqm2iufO6U&libraries=places&loading=async&callback=initMap" async defer>
      </script>

      {/* <Script id="GoogleMaps" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBOjiEhtSB9GwO0UJGqzlDkJvqm2iufO6U&libraries=places&loading=async&callback=initMap" async defer>
      </Script> */}

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <ContextProvider>
            <main className="min-h-screen flex flex-col">
              {children}
            </main>
          </ContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
